/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_javashell_video_ingestors_QOIStreamIngestorC */

#ifndef _Included_com_javashell_video_ingestors_QOIStreamIngestorC
#define _Included_com_javashell_video_ingestors_QOIStreamIngestorC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_javashell_video_ingestors_QOIStreamIngestorC
 * Method:    decode
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_javashell_video_ingestors_QOIStreamIngestorC_decode
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
