/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_javashell_video_egressors_cl_QOIStreamEgressorC */

#ifndef _Included_com_javashell_video_egressors_cl_QOIStreamEgressorC
#define _Included_com_javashell_video_egressors_cl_QOIStreamEgressorC
#ifdef __cplusplus
extern "C" {
#endif
#undef com_javashell_video_egressors_cl_QOIStreamEgressorC_frameRateInterval
#define com_javashell_video_egressors_cl_QOIStreamEgressorC_frameRateInterval 16000000LL

/*
 * Class:     com_javashell_video_egressors_cl_QOIStreamEgressorC
 * Method:    encode
 * Signature: ([BIIIIZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_javashell_video_egressors_cl_QOIStreamEgressorC_encodeB
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint, jint, jboolean);


JNIEXPORT jbyteArray JNICALL Java_com_javashell_video_egressors_cl_QOIStreamEgressorC_encodei
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jint, jint, jboolean);

#ifdef __cplusplus=
}
#endif
#endif
