/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_javashell_video_ingestors_NDI5Ingestor */

#ifndef _Included_com_javashell_video_ingestors_NDI5Ingestor
#define _Included_com_javashell_video_ingestors_NDI5Ingestor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_javashell_video_ingestors_NDI5Ingestor
 * Method:    grabFrame
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_javashell_video_ingestors_NDI5Ingestor_grabFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_javashell_video_ingestors_NDI5Ingestor
 * Method:    initializeNDI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_javashell_video_ingestors_NDI5Ingestor_initializeNDI
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
