/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_javashell_video_egressors_cl_QOIStreamEgressorC */

#ifndef _Included_com_javashell_video_egressors_cl_QOIStreamEgressorC
#define _Included_com_javashell_video_egressors_cl_QOIStreamEgressorC
#ifdef __cplusplus
extern "C" {
#endif
#undef com_javashell_video_egressors_cl_QOIStreamEgressorC_frameRateInterval
#define com_javashell_video_egressors_cl_QOIStreamEgressorC_frameRateInterval 16000000LL
/*
 * Class:     com_javashell_video_egressors_cl_QOIStreamEgressorC
 * Method:    encode
 * Signature: ([B[BIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_javashell_video_egressors_cl_QOIStreamEgressorC_encode
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
