/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_javashell_video_ingestors_QOYStreamIngestor */

#ifndef _Included_com_javashell_video_ingestors_QOYStreamIngestor
#define _Included_com_javashell_video_ingestors_QOYStreamIngestor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_javashell_video_ingestors_QOYStreamIngestor
 * Method:    decode
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_javashell_video_ingestors_QOYStreamIngestor_decode
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
