/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_javashell_video_egressors_LibVPXStreamEgressor */

#ifndef _Included_com_javashell_video_egressors_LibVPXStreamEgressor
#define _Included_com_javashell_video_egressors_LibVPXStreamEgressor
#ifdef __cplusplus
extern "C" {
#endif
#undef com_javashell_video_egressors_LibVPXStreamEgressor_frameRateInterval
#define com_javashell_video_egressors_LibVPXStreamEgressor_frameRateInterval 16000000LL
/*
 * Class:     com_javashell_video_egressors_LibVPXStreamEgressor
 * Method:    initializeVPX
 * Signature: (IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_javashell_video_egressors_LibVPXStreamEgressor_initializeVPX
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     com_javashell_video_egressors_LibVPXStreamEgressor
 * Method:    sendFrameB
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_com_javashell_video_egressors_LibVPXStreamEgressor_sendFrameB
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_javashell_video_egressors_LibVPXStreamEgressor
 * Method:    sendFrameI
 * Signature: (J[II)V
 */
JNIEXPORT void JNICALL Java_com_javashell_video_egressors_LibVPXStreamEgressor_sendFrameI
  (JNIEnv *, jobject, jlong, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
